# -*- coding: utf-8 -*-
"""Untitled191.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIMO2u36Hxdr5_pjtda-KfveftpwtqIA
"""

import streamlit as st

st.title("My First App")

name = st.text_input("Enter your name:")

if name:
    st.write("Hello,", name)

!pip install streamlit

import streamlit as st

st.title("My First App")

name = st.text_input("Enter your name:")

if name:
    st.write("Hello,", name)

import streamlit as st

st.title("My First App")
st.write("Hello World")